POST https://todo-api.wonderfulbeach-47cacaf7.northeurope.azurecontainerapps.io/v1/todos
X-API_KEY: <Insert your API key>
Content-Type: application/json

{
    "title": "Learn Rust",
    "description": "Learn Rust by building a RESTful API"
}